### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by sjoerdapp** [nschmidtg/thesis#27]
Hi 🖖🏼,  I was wondering if you could provide a working link to the zip files? Your thesis is looking very interesting, and the effort it in good training database is under appreciated. It is the difference between a home run and sloppy shot.

**Comment by nschmidtg** [comment]
> Hi 🖖🏼, I was wondering if you could provide a working link to the zip files? Your thesis is looking very interesting, and the effort it in good training database is under appreciated. It is the difference between a home run and sloppy shot.

Hey @sjoerdapp sorry for the late reply! Please [refer to this repo ](https://github.com/MTG/PodcastMix)for full download links, papers, installation, train and evaluate instructions :) Thanks a lot for the interest!!
